version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: my-web-nginx-3
    ports:
      - "8083:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Relative path for nginx.conf
    depends_on:
      - web

  web:
    image: python:3.9-alpine
    container_name: my-web-python-3
    volumes:
      - ./app.py:/app/app.py # Relative path for app.py
    command: sh -c "pip install redis flask && python /app/app.py"
    depends_on:
      - redis
  
  redis:
    image: redis:alpine
    container_name: my-web-redis-3
    volumes:
      - ./redis_data:/data